package model

import (
	"context"
	"errors"
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var (
	ErrZTAPIHealthCircuitOpen        = errors.New("ztapi model temporarily unavailable")
	ErrZTAPIHealthRouteOpen          = errors.New("ztapi upstream route temporarily unavailable")
	ErrZTAPIHealthGenerationConflict = errors.New("ztapi health generation conflict")
	ErrZTAPIHealthExecutionConflict  = errors.New("ztapi health execution already admitted")
	ErrZTAPIHealthInvalidTicket      = errors.New("ztapi health invalid admission ticket")
	ErrZTAPIHealthLeaseConflict      = errors.New("ztapi health outbox lease conflict")
	ErrZTAPIHealthTestAlertInvalid   = errors.New("ztapi health test alert requires a UUID operation and operator")
	ErrZTAPIHealthInvalidReceipt     = errors.New("invalid ztapi health delivery receipt")
)

type ZTAPIHealthState struct {
	ModelID             int    `gorm:"primaryKey;autoIncrement:false"`
	Generation          uint64 `gorm:"not null"`
	CompletionSequence  uint64 `gorm:"not null"`
	ConsecutiveFailures int64  `gorm:"not null"`
	Open                bool   `gorm:"not null;index"`
	IncidentID          int64  `gorm:"not null"`
	UpdatedAt           int64  `gorm:"not null"`
}

func (ZTAPIHealthState) TableName() string { return "ztapi_health_states" }

// Admission survives process death; execution IDs are generated by the gateway.
type ZTAPIHealthRequest struct {
	ExecutionID   string `gorm:"primaryKey;size:128"`
	RequestID     string `gorm:"size:255;not null;index"`
	ModelID       int    `gorm:"not null;index"`
	ConfigVersion uint64 `gorm:"not null"`
	Generation    uint64 `gorm:"not null"`
	PublicModel   string `gorm:"size:255;not null"`
	Modality      string `gorm:"size:32;not null;default:text"`
	Operation     string `gorm:"size:32;not null;default:''"`
	EntryProtocol string `gorm:"size:32;not null;default:''"`
	UserID        int    `gorm:"not null"`
	Stream        bool   `gorm:"not null"`
	Source        string `gorm:"size:16;not null"`
	StartedAt     int64  `gorm:"not null;index:idx_zt_health_orphans,priority:2"`
	Completed     bool   `gorm:"not null;index:idx_zt_health_orphans,priority:1"`
	Admissions    string `gorm:"type:text;not null"`
}

func (ZTAPIHealthRequest) TableName() string { return "ztapi_health_requests" }

// CompletionSequence is assigned under the model's write lock, not at arrival.
type ZTAPIHealthEvent struct {
	ID                  int64  `gorm:"primaryKey"`
	ExecutionID         string `gorm:"size:128;not null;uniqueIndex"`
	RequestID           string `gorm:"size:255;not null;index"`
	ModelID             int    `gorm:"not null;uniqueIndex:idx_zt_health_sequence,priority:1;index:idx_zt_health_window,priority:1"`
	ConfigVersion       uint64 `gorm:"not null"`
	Generation          uint64 `gorm:"not null"`
	PublicModel         string `gorm:"size:255;not null"`
	Modality            string `gorm:"size:32;not null;default:text"`
	Operation           string `gorm:"size:32;not null;default:'';index"`
	EntryProtocol       string `gorm:"size:32;not null;default:''"`
	CompletionSequence  uint64 `gorm:"not null;uniqueIndex:idx_zt_health_sequence,priority:2"`
	CompletedAt         int64  `gorm:"not null;index:idx_zt_health_window,priority:2"`
	Stream              bool   `gorm:"not null"`
	Source              string `gorm:"size:16;not null"`
	Result              string `gorm:"size:16;not null"`
	Reason              string `gorm:"size:128;not null"`
	Counted             bool   `gorm:"not null"`
	StaleGeneration     bool   `gorm:"not null"`
	ChannelID           int    `gorm:"not null"`
	CredentialVersion   string `gorm:"size:64;not null;default:''"`
	UpstreamProtocol    string `gorm:"size:64;not null"`
	HTTPStatus          int    `gorm:"not null"`
	UpstreamRequestID   string `gorm:"size:255;not null"`
	UpstreamTaskID      string `gorm:"size:255;not null"`
	ProviderErrorCode   string `gorm:"size:128;not null"`
	LatencyMilliseconds int64  `gorm:"not null;default:0"`
	ResultValid         bool   `gorm:"not null;default:false"`
	Outcome             string `gorm:"type:text;not null"`
}

func (ZTAPIHealthEvent) TableName() string { return "ztapi_health_events" }

type ZTAPIHealthIncident struct {
	ID                  int64  `gorm:"primaryKey"`
	ModelID             int    `gorm:"not null;uniqueIndex:idx_zt_health_incident_generation,priority:1"`
	Generation          uint64 `gorm:"not null;uniqueIndex:idx_zt_health_incident_generation,priority:2"`
	ConfigVersion       uint64 `gorm:"not null"`
	PublicModel         string `gorm:"size:255;not null"`
	TriggerEventID      int64  `gorm:"not null"`
	VerificationCaseID  string `gorm:"size:36;not null;default:'';index"`
	Rule                string `gorm:"size:64;not null"`
	ConsecutiveFailures int64  `gorm:"not null"`
	ValidSamples        int64  `gorm:"not null"`
	Failures            int64  `gorm:"not null"`
	WindowStart         int64  `gorm:"not null"`
	OpenedAt            int64  `gorm:"not null"`
	UnpublishedAt       int64  `gorm:"not null"`
	UnpublishedVersion  uint64 `gorm:"not null"`
	RecoveredAt         int64  `gorm:"not null"`
	RecoveryOperatorID  int    `gorm:"not null"`
	RecoveryEvidence    string `gorm:"type:text;not null"`
}

func (ZTAPIHealthIncident) TableName() string { return "ztapi_health_incidents" }

type ZTAPIHealthOutbox struct {
	ID                 int64  `gorm:"primaryKey"`
	DedupKey           string `gorm:"size:191;not null;uniqueIndex"`
	Kind               string `gorm:"size:32;not null;index:idx_zt_health_due,priority:1"`
	ModelID            int    `gorm:"not null;index"`
	Generation         uint64 `gorm:"not null"`
	IncidentID         int64  `gorm:"not null;index"`
	EventID            int64  `gorm:"not null"`
	VerificationCaseID string `gorm:"size:36;not null;default:'';index"`
	Status             string `gorm:"size:16;not null;index:idx_zt_health_due,priority:2"`
	Attempts           int    `gorm:"not null"`
	NextAttemptAt      int64  `gorm:"not null;index:idx_zt_health_due,priority:3"`
	LeaseUntil         int64  `gorm:"not null"`
	LeaseToken         string `gorm:"size:64;not null"`
	LastError          string `gorm:"size:255;not null"`
	CreatedAt          int64  `gorm:"not null"`
	DeliveredAt        int64  `gorm:"not null"`
	DeliveryReceipt    string `gorm:"type:text"`
}

func (ZTAPIHealthOutbox) TableName() string { return "ztapi_health_outbox" }

func migrateZTAPIHealthVerificationLegacy(db *gorm.DB) error {
	if db == nil {
		return errors.New("ztapi health database is not initialized")
	}
	if db.Migrator().HasTable(&ZTAPIHealthVerificationCase{}) {
		legacyWindow := db.Migrator().HasColumn(&ZTAPIHealthVerificationCase{}, "window")
		if db.Migrator().HasIndex(&ZTAPIHealthVerificationCase{}, "idx_ztapi_verify_window") {
			if err := db.Migrator().DropIndex(&ZTAPIHealthVerificationCase{}, "idx_ztapi_verify_window"); err != nil {
				return err
			}
		}
		if legacyWindow {
			if err := db.Migrator().DropColumn(&ZTAPIHealthVerificationCase{}, "window"); err != nil {
				return err
			}
		}
	}
	return nil
}

func cancelOrphanedZTAPIHealthVerificationCases(db *gorm.DB) error {
	return db.Transaction(func(tx *gorm.DB) error {
		var active []ZTAPIHealthVerificationCase
		if err := tx.Where("state IN ?", []string{"queued", "claimed"}).Find(&active).Error; err != nil {
			return err
		}
		cancelledAt := time.Now().UTC().UnixMilli()
		for _, verificationCase := range active {
			var gateCount int64
			if err := tx.Model(&ZTAPIHealthVerificationGate{}).
				Where("model_id = ? AND channel_id = ? AND entry_protocol = ? AND protocol = ? AND stream = ? AND credential_version = ? AND generation = ? AND active_case_id = ?",
					verificationCase.ModelID, verificationCase.ChannelID, verificationCase.EntryProtocol, verificationCase.Protocol, verificationCase.Stream,
					verificationCase.CredentialVersion, verificationCase.Generation, verificationCase.ID).
				Count(&gateCount).Error; err != nil {
				return err
			}
			if gateCount != 0 {
				continue
			}
			if err := tx.Model(&ZTAPIHealthVerificationCase{}).
				Where("id = ? AND state IN ?", verificationCase.ID, []string{"queued", "claimed"}).
				Updates(map[string]any{
					"state":        "cancelled",
					"cancelled_at": cancelledAt,
					"lease_token":  "",
					"lease_until":  0,
				}).Error; err != nil {
				return err
			}
		}
		return nil
	})
}

func MigrateZTAPIHealth(db *gorm.DB) error {
	if err := migrateZTAPIHealthVerificationLegacy(db); err != nil {
		return err
	}
	if err := db.AutoMigrate(
		&ZTAPIHealthState{},
		&ZTAPIHealthRequest{},
		&ZTAPIHealthEvent{},
		&ZTAPIHealthIncident{},
		&ZTAPIHealthOutbox{},
		&ZTAPIHealthVerificationCase{},
		&ZTAPIHealthVerificationGate{},
		&ZTAPIHealthRouteState{},
		&ZTAPIHealthProbeEvidence{},
	); err != nil {
		return err
	}
	return cancelOrphanedZTAPIHealthVerificationCases(db)
}

type ZTAPIHealthStore struct {
	DB *gorm.DB
	// Now is replaceable for deterministic tests. Do not mutate it while in use.
	Now            func() time.Time
	transactionFn  func(context.Context, func(*gorm.DB) error) error
	afterStateLock func()
	retryObserver  func(error)
}

func NewZTAPIHealthStore(db *gorm.DB) *ZTAPIHealthStore {
	return &ZTAPIHealthStore{DB: db, Now: time.Now}
}

func (s *ZTAPIHealthStore) now() int64 { return s.Now().UTC().Unix() }

// Retry only complete, rolled-back DB transactions; no network side effects.
// The first statement in health transactions obtains a write lock. In SQLite
// this avoids deferred read-to-write upgrades; InnoDB serializes the model row.
func (s *ZTAPIHealthStore) transaction(ctx context.Context, fn func(*gorm.DB) error) error {
	if s == nil || s.DB == nil {
		return errors.New("ztapi health database is not initialized")
	}
	if s.transactionFn != nil {
		return s.transactionFn(ctx, fn)
	}
	for attempt := 0; ; attempt++ {
		err := s.DB.WithContext(ctx).Transaction(fn)
		if err == nil || attempt >= 11 || !ztapiHealthRetryable(err) {
			return err
		}
		if s.retryObserver != nil {
			s.retryObserver(err)
		}
		timer := time.NewTimer(time.Duration(5*(attempt+1)) * time.Millisecond)
		select {
		case <-ctx.Done():
			timer.Stop()
			return ctx.Err()
		case <-timer.C:
		}
	}
}

func ztapiHealthRetryable(err error) bool {
	m := strings.ToLower(err.Error())
	return strings.Contains(m, "database is locked") || strings.Contains(m, "database table is locked") ||
		strings.Contains(m, "sqlite_busy") || strings.Contains(m, "deadlock") ||
		strings.Contains(m, "lock wait timeout") || strings.Contains(m, "could not serialize access")
}

func lockZTAPIHealthState(tx *gorm.DB, modelID int) (*ZTAPIHealthState, error) {
	state := ZTAPIHealthState{ModelID: modelID, Generation: 1}
	if err := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(&state).Error; err != nil {
		return nil, err
	}
	if err := tx.Model(&ZTAPIHealthState{}).Where("model_id = ?", modelID).
		UpdateColumn("generation", gorm.Expr("generation")).Error; err != nil {
		return nil, err
	}
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&state, "model_id = ?", modelID).Error; err != nil {
		return nil, err
	}
	return &state, nil
}

func (s *ZTAPIHealthStore) GetState(ctx context.Context, modelID int) (*ZTAPIHealthState, error) {
	var state ZTAPIHealthState
	err := s.DB.WithContext(ctx).First(&state, "model_id = ?", modelID).Error
	return &state, err
}

type ZTAPIHealthWindow struct {
	ValidSamples int64
	Failures     int64
	WindowStart  int64
	WindowEnd    int64
}

func ztapiHealthWindow(tx *gorm.DB, modelID int, now int64) (ZTAPIHealthWindow, error) {
	w := ZTAPIHealthWindow{WindowStart: now - 86400, WindowEnd: now}
	err := tx.Model(&ZTAPIHealthEvent{}).
		Select("COUNT(*) AS valid_samples, COALESCE(SUM(CASE WHEN result = 'failure' THEN 1 ELSE 0 END), 0) AS failures").
		Where("model_id = ? AND counted = ? AND completed_at > ? AND completed_at <= ?", modelID, true, w.WindowStart, now).Scan(&w).Error
	return w, err
}

func (s *ZTAPIHealthStore) Window(ctx context.Context, modelID int) (ZTAPIHealthWindow, error) {
	return ztapiHealthWindow(s.DB.WithContext(ctx), modelID, s.now())
}

func ztapiHealthLimit(limit int) int {
	if limit <= 0 || limit > 100 {
		return 100
	}
	return limit
}

func (s *ZTAPIHealthStore) ListEvents(ctx context.Context, modelID int, afterSequence uint64, limit int) ([]ZTAPIHealthEvent, error) {
	var events []ZTAPIHealthEvent
	err := s.DB.WithContext(ctx).Where("model_id = ? AND completion_sequence > ?", modelID, afterSequence).
		Order("completion_sequence ASC").Limit(ztapiHealthLimit(limit)).Find(&events).Error
	return events, err
}
